version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html/
  - source: /BSTests
    destination: /var/www/BSTests/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: ec2-user