name: Deploy CI
on:
  push:
    branches: [ test ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x op.sh
    - run: ./op.sh build
    - run: ./op.sh deploy
