name: Deploy CI
on:
  push:
    branches: [ test ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: /home/ec2-user/tmp/actions-runner/_work/funding-vue/funding-vue/op.sh build
    - run: /home/ec2-user/tmp/actions-runner/_work/funding-vue/funding-vue/op.sh deploy
