name: Build、Deploy and Test CI
on:
  push:
    branches: [ test ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x op.sh
    - name: build and deploy
      run: |
        ./op.sh build
        ./op.sh deploy
    - name: pytest with selenium in browserstack
      run: |
        pytest BSTests/test.py --html=/home/ec2-user/reports/${GITHUB_REF#refs/heads/}.${GITHUB_SHA}.report.html 
    - name: Print the report
      if: always() # shell: bash
      run: |
        value=`cat /home/ec2-user/reports/${GITHUB_REF#refs/heads/}.${GITHUB_SHA}.report.html`
        echo The result is $value
        echo https://www.runoob.com/runcode